export const GET_CATASTROPHES = 'GET_CATASTROPHES';
export const GET_CATASTROPHE_SUCCESS = 'GET_CATASTROPHE_SUCCESS';
export const GET_CATASTROPHE_ERROR = 'GET_CATASTROPHE_ERROR';


export const GET_WITH_PAGINATE_CATASTROPHES = 'GET_WITH_PAGINATE_CATASTROPHES';
export const GET_WITH_PAGINATE_CATASTROPHE_SUCCESS = 'GET_WITH_PAGINATE_CATASTROPHE_SUCCESS';
export const GET_WITH_PAGINATE_CATASTROPHE_ERROR = 'GET_WITH_PAGINATE_CATASTROPHE_ERROR';

export const POST_CATASTROPHES = 'POST_CATASTROPHES';
export const POST_CATASTROPHE_SUCCESS = 'POST_CATASTROPHE_SUCCESS';
export const POST_CATASTROPHE_ERROR = 'POST_CATASTROPHE_ERROR';

export const PUT_CATASTROPHES = 'PUT_CATASTROPHES';
export const PUT_CATASTROPHE_SUCCESS = 'PUT_CATASTROPHE_SUCCESS';
export const PUT_CATASTROPHE_ERROR = 'PUT_CATASTROPHE_ERROR';

export const DEL_CATASTROPHES = 'DEL_CATASTROPHES';
export const DEL_CATASTROPHE_SUCCESS = 'DEL_CATASTROPHE_SUCCESS';
export const DEL_CATASTROPHE_ERROR = 'DEL_CATASTROPHE_ERROR';

export const SHOW_CATASTROPHE = 'SHOW_CATASTROPHES';
export const SHOW_CATASTROPHE_SUCCESS = 'SHOW_CATASTROPHE_SUCCESS';
export const SHOW_CATASTROPHE_ERROR = 'SHOW_CATASTROPHE_ERROR';
